stages:
  prepare_data_for_model:
    cmd: python -m src prepare_data_for_model
    outs:
    - data/data_for_models
  train_pass_success_model:
    cmd: python -m src train_pass_success_model
    deps:
    - data/data_for_models
    params:
    - seed
    - train_pass_success_model.split
    outs:
    - models/pass_success_lgbm.joblib
  evaluate_pass_success_model:
    cmd: python -m src evaluate_pass_success_model
    deps:
    - models/pass_success_lgbm.joblib
    params:
    - seed
    outs:
    - reports/pass_success_model_evaluation
  create_match_networks:
    cmd: python -m src create_match_networks
    deps:
    - models/pass_success_lgbm.joblib
    params:
    - seed
    outs:
    - data/networks
  create_style_data:
    cmd: python -m src create_style_data
    deps:
    - data/networks
    params:
    - seed
    outs:
    - data/style
